{
  "schema_version": "1.4.0",
  "id": "GHSA-r3xc-prgr-mg9p",
  "modified": "2024-04-03T14:59:15Z",
  "published": "2023-05-07T03:30:17Z",
  "aliases": [
    "CVE-2023-31047"
  ],
  "summary": "Django bypasses validation when using one form field to upload multiple files",
  "details": "In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.forms.widgets.FileInput"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.2"
            },
            {
              "fixed": "3.2.19"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.forms.widgets.FileInput"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.0"
            },
            {
              "fixed": "4.1.9"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.forms.widgets.FileInput"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.2"
            },
            {
              "fixed": "4.2.1"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-31047"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/21b1b1fc03e5f9e9f8c977ee6e35618dd3b353dd"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/e7c3a2ccc3a562328600be05068ed9149e12ce64"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/eed53d0011622e70b936e203005f0e6f4ac48965"
    },
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/4.2/releases/security"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/django/django"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-61.yaml"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/forum/#!forum/django-announce"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A45VKTUVQ2BN6D5ZLZGCM774R6QGFOHW"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNEHD6N435OE2XUFGDAAVAXSYWLCUBFD"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20230609-0008"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2023/may/03/security-releases"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2023-05-09T21:35:46Z",
    "nvd_published_at": "2023-05-07T02:15:08Z"
  }
}