{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-6975",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "https://www.djangoproject.com/weblog/2019/feb/11/security-releases/",
                "refsource": "MISC",
                "url": "https://www.djangoproject.com/weblog/2019/feb/11/security-releases/"
            },
            {
                "name": "https://docs.djangoproject.com/en/dev/releases/security/",
                "refsource": "MISC",
                "url": "https://docs.djangoproject.com/en/dev/releases/security/"
            },
            {
                "name": "106964",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/106964"
            },
            {
                "name": "USN-3890-1",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3890-1/"
            },
            {
                "name": "https://www.openwall.com/lists/oss-security/2019/02/11/1",
                "refsource": "MISC",
                "url": "https://www.openwall.com/lists/oss-security/2019/02/11/1"
            },
            {
                "name": "https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ",
                "refsource": "MISC",
                "url": "https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-5ad2149e99",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-f528d75a69",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/"
            },
            {
                "refsource": "DEBIAN",
                "name": "DSA-4476",
                "url": "https://www.debian.org/security/2019/dsa-4476"
            },
            {
                "refsource": "BUGTRAQ",
                "name": "20190708 [SECURITY] [DSA 4476-1] python-django security update",
                "url": "https://seclists.org/bugtraq/2019/Jul/10"
            }
        ]
    }
}